class Error:
    def run(self, *args):
        raise Exception("Fail!")